### ISSUE TITLE
background(#, #, #, ALPHA) not working in Jupyter notebook

### ISSUE THREAD

**Issue by sawula** [hx2A/py5generator#22]
```
%%py5draw 200 200
background(0,0,255,50)
background(0,255,0,50)
```

has output of solid green.  Changing the alpha values to 0.5 has no effect.  

Running this in a 'desktop' Jupyter notebook.

***NVM.  It's not behaving the way I expected in processing.py or regular processing.***

**Comment by hx2A** [comment]
This is helpful, you have pointed out a relevant issue with the `%%py5draw` documentation that I would like to fix.

The arguments to the [background](http://py5.ixora.io/reference/background/) function are controlled by the [color_mode](http://py5.ixora.io/reference/color_mode/) function.

The [background](http://py5.ixora.io/reference/background/) function documentation says that it is not possible to use the transparency parameter when drawing on the main drawing surface.

The part that is not transparent (sorry for the pun...) is the [%%py5draw](http://py5.ixora.io/reference/py5draw/) documentation. When you use that magic command it isn't clear that the code in the cell is getting executed on a main drawing surface, and therefore the background function cannot use the transparency parameter. I should add a sentence or two to make that more clear.

There is an easy way to create transparent images, and that is with the render helper tools. Have a look at the last example for [@render()](http://py5.ixora.io/reference/render/) and [render_frame()](http://py5.ixora.io/reference/render_frame/). Both can do what you want by letting you draw on a `Py5Graphics` object, which does allow `background()` to be transparent.

**Comment by hx2A** [comment]
I just improved the documentation with https://github.com/hx2A/py5generator/commit/607b15e5c1e631726d30eff7d4aeed617314b04e , which includes changes to %%py5draw. It will be pushed to the website when I do the next release, which will likely (hopefully) be this weekend.

Thanks again for opening the issue.
