### ISSUE TITLE
Dependency on noise library will cause installation challenges for users who are not using Anaconda

### ISSUE THREAD

**Issue by hx2A** [hx2A/py5generator#38]
Dependency on noise library will cause installation challenges for users who are not using Anaconda. The noise library does not seem to be currently maintained by the package owner and there are not current wheels being uploaded to pypi. The library requires compilation because it uses c code. This can be a challenge for folks on Windows in particular, where installing the c compiler requires a bunch of downloads.

What other noise library alternatives are there? Should py5 use its own implementation of the noise algorithms?

**Comment by hx2A** [comment]
Possible replacement candidate: https://github.com/plottertools/vnoise

**Comment by hx2A** [comment]
The noise library has been removed from py5 and has been replaced with opensimplex and Processing's noise functionality. Will be available after the next release.

**Comment by tabreturn** [comment]
Thanks @hx2A! When is this release out?

**Comment by hx2A** [comment]
My goal is to do a release by the end of January. I need to finish up things with Py5Vector first. Py5Vector is basically done, I am just finishing the documentation.
