### ISSUE TITLE
Error caused by setup.py location

### ISSUE THREAD

**Issue by JBwdn** [hx2A/py5generator#50]
I have found that the package biopython has import issues as a result of the py5 setup.py file. This case is solved easily for the time being with envs since I dont use them together but is there scope for other package import clashing?

> /home/jbwdn/miniconda3/lib/python3.9/site-packages/Bio/__init__.py:118: BiopythonWarning: You may be importing Biopython from inside the source tree. This is bad practice and might lead to downstream issues. In particular, you might encounter ImportErrors due to missing compiled C extensions. We recommend that you try running your code from outside the source tree. If you are outside the source tree then you have a setup.py file in an unexpected directory: /home/jbwdn/miniconda3/lib/python3.9/site-packages

**Comment by hx2A** [comment]
Can I have some more information here? @codeanticode, is this related to your project?

**Comment by codeanticode** [comment]
Cannot tell but it's possible, Sciviewer does not have a direct dependency on biopython:

https://github.com/colabobio/sciviewer/blob/master/sciviewer-env.yml

but maybe through scanpy?

@JBwdn are you using/trying to install this https://github.com/colabobio/sciviewer by any chance ?

**Comment by hx2A** [comment]
@JBwdn How did you install biopython? I Googled that error message and it seems that is something specific to biopython and is something others have had issues with. How did you make a connection from biopython to py5?

**Comment by JBwdn** [comment]
Hi both, I was just testing py5 in my base conda env, but when I went back to some work which imports biopython (import Bio) this error occurs. I wasn't working with sciviewer at all. 

I made the link to py5 since the setup.py file in site-packages which is causing the error belongs to py5.

A minimal environment which shows the same error is just `pip install py5 Bio`.

This isnt a big deal for me, but maybe the location of this file on your end will cause import problems with more packages than just bio. 
Cheers, Jake

**Comment by hx2A** [comment]
Thank you, I can now reproduce the problem. I created two conda environments, both with python 3.9 and Bio, but only one with py5. When I import Bio in the environment that has py5 I get that error message. The other one does not.

```
/home/jim/INSTALL/anaconda3/envs/bugtest/lib/python3.9/site-packages/Bio/__init__.py:118: BiopythonWarning: You may be importing Biopython from insi
de the source tree. This is bad practice and might lead to downstream issues. In particular, you might encounter ImportErrors due to missing compile
d C extensions. We recommend that you try running your code from outside the source tree. If you are outside the source tree then you have a setup.p
y file in an unexpected directory: /home/jim/INSTALL/anaconda3/envs/bugtest/lib/python3.9/site-packages
```

When I go into the directory `/home/jim/INSTALL/anaconda3/envs/bugtest/lib/python3.9/site-packages` I see there is the file `setup.py` sitting there. Perhaps that file is getting included in the packaging process. I'll take a closer look at this and compare it to other library's packaging to see what I'm doing differently.

@JBwdn thanks for taking the time to report this bug, I appreciate it. I'm planning on doing a release with in a month and will fix this soon.

**Comment by hx2A** [comment]
Small packaging error. Will be fixed in the next release
