### ISSUE TITLE
how help with examples and tutorial?

### ISSUE THREAD

**Issue by edurojasr** [hx2A/py5generator#56]
I apologize if this is no the place to ask, but I want to help in writing documentation on examples and tutorials, Im using py5 with a openjdk snap for Ubuntu and works great, so I think I may help with example code and tutorial but I don't know where and how to start

**Comment by hx2A** [comment]
Hello, and welcome!

A while back I started a [discussion thread for my thoughts on documentation](https://github.com/hx2A/py5generator/discussions/21), so perhaps we can talk about it there. I certainly do need help writing documentation and tutorials, particularly for people new to the processing ecosystem.

Have you used Jupyter Book? Are you comfortable using Jupyter notebooks? If not you should try experimenting with both of these to see how they work. The current py5 documentation website uses Jupyter Book, which can make heavy use of notebooks.

**Comment by edurojasr** [comment]
Sure! I would read that thread first!
Thnaks :)

**Comment by tabreturn** [comment]
@edurojasr https://github.com/processing/processing/wiki/Project-List#-py5

**Comment by hx2A** [comment]
@edurojasr , if you are still interested, we'd love to have your help!

**Comment by edurojasr** [comment]
Hi @hx2A
Sure! I'm reading the wiki and getting started with jupyter notebooks. (I apologize for my absence, but my work and study have taken a lot of time as I am preparing to start my thesis)

**Comment by hx2A** [comment]
@edurojasr no need to explain, everyone here has many competing priorities! A thesis is a lot of work!
