### ISSUE TITLE
On OSX, py5_tools.save_frames(), animated_gif(), and capture_frames() trip up the animation thread

### ISSUE THREAD

**Issue by hx2A** [hx2A/py5generator#58]
The functions do not return after adding the hooks because it prints out progress messages. Those progress messages should be handled differently or skipped altogether.

**Comment by hx2A** [comment]
Can `capture_frames()` even be useful on OSX?

**Comment by hx2A** [comment]
Totally rebuilt these methods so they can return right away and work on OSX. The progress messages are printed to the Jupyter output cell associated with the code, and allows the user to move on to another cell while these are running.

**Comment by villares** [comment]
Have you tested `py5_tools.animated_gif(}` outside the Jupyter environment?
I couldn't make it work yet, but I know a new release is coming out, I think next week I'll ask you some questions about this...

**Comment by hx2A** [comment]
I believe they will work with the generic Python interpreter but it doesn't look like they will work with the run_sketch command line utility. However, it would be great if that was possible, because this would be great functionality to make available for Thonny users. Looking at the code, I see where the issue is, but am not comfortable modifying that right before a release. It shouldn't be a big deal to fix this. I'll add it to the todo list for the release after this upcoming one.
