### ISSUE TITLE
text() behaviour seemed surprising with non-string argument

### ISSUE THREAD

**Issue by villares** [hx2A/py5generator#65]
In my experience, the Processing text function converts numerical values to strings when they are placed as the first argument (the text content). 

The Processing documentation (and py5 following it) hint at the possibility of a "char" value, I never say this in either Java or Python modes.  As it is now py5 is always interpreting int values as "chars" or "code point values", and this is surprising for me.

I think the Processing Java documentation could be wrong or something else is going on that I don't understand...

Here a summary image of my investigations:
![image](https://user-images.githubusercontent.com/3694604/152689740-1101c7e4-9b19-4a74-a33b-ad18fa6228f8.png)

**Comment by hx2A** [comment]
Interesting. I recall fixing this recently but can't remember if it was before or after the last release. Can you confirm which version you are using right now? I will double check the code.

**Comment by hx2A** [comment]
I just tested it and got the correct behavior. This fix is in the latest release.

Can you run this to check your version number?

```
def setup():
    text(65, 40, 40)
    print(__version__)
```

**Comment by villares** [comment]
That was it! I had an older version on this env!
![image](https://user-images.githubusercontent.com/3694604/152690797-8b1f4749-3ec3-4573-b13d-7d696d733098.png)

**Comment by hx2A** [comment]
You have a good eye for catching this!

**Comment by villares** [comment]
hahah, thanks... but I should always check the version before reporting issues... :man_facepalming:

**Comment by hx2A** [comment]
No worries, we've all been there
