### ISSUE TITLE
[MacOS] Assertion failure in +[NSEvent with RecursionError

### ISSUE THREAD

**Issue by evayann** [hx2A/py5generator#72]
When I create a simple sketch, I have a lot of Assertion failure who finish with RecursionError. 
You can find pdf who describe this bellow.
[simple_example.pdf](https://github.com/hx2A/py5generator/files/8355406/simple_example.pdf)

**Comment by hx2A** [comment]
Interesting. Can you tell me how you created your environment? Is your computer one of the new Apple Silicon machines?

**Comment by evayann** [comment]
For environment, I install Jupyter from brew (and pip to execute jupyter in vscode)
My MacBook is MacBook Air M1 with first release on November 2020

**Comment by hx2A** [comment]
> My MacBook is MacBook Air M1 (Apple Silicon)

Hmmm, I guess this answers [my question about if py5 works on Apple Silicon](https://ixora.io/blog/new-release-071a6/). I'm surprised the default renderer doesn't work. I thought only P2D and P3D would cause problems.

I need some time to think and figure out next steps. Would you be willing to help me test new versions of py5 as I come up with ideas to address this?

**Comment by hx2A** [comment]
Today's release of py5 should fix most (or all) of the OSX problems. Please read the rewritten [Special Notes for OSX Users](http://py5.ixora.io/content/osx_users.html) page and create a new issue if you see something that doesn't work. I'm curious if there are any problems on Apple Silicon machines. Thank you for your interest in this project!
